name: Build and deploy Vite app to Azure Web App - nutrinova

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '24.x'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload dist folder
        uses: actions/upload-artifact@v4
        with:
          name: vite-build
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: vite-build
          path: dist

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: nutrinova
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: dist

          




